###
GET http://localhost:3001/

###
GET http://localhost:3001/api/users

###
POST  http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "MAtheus",
  "password": "123456",
  "role": "USER"
}

###
PATCH http://localhost:3001/api/products/5e758b40-6c51-48c7-b909-49cb4ea6c85d
Content-Type: application/json

{
  "name": "Happy sugar",
  "price": 6.00
}


###
DELETE http://localhost:3001/api/products/549c0671-f828-495c-9a8b-6df1fdfa6833
